services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  owner_service:
    build: ./owner_service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_DB: owner_service
    ports:
      - "8001:8000"


  ranger-service:
    build: ./ranger_service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_DB: ranger_service
    ports:
      - "8002:8000"

  plant-service:
    build: ./plant_service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_DB: plant_service
    ports:
      - "8003:8000"

  task-service:
    build: ./task_service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_DB: task_service
    ports:
      - "8004:8000"


volumes:
  pgdata:
